#version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud_password
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin_password
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 127.0.0.1
    volumes:
      - ./nextcloud_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - nextcloud_network

  db:
    image: mariadb:latest
    container_name: nextcloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud_password
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - nextcloud_network

  redis:
    image: redis:latest
    container_name: nextcloud_redis
    restart: always
    networks:
      - nextcloud_network

networks:
  nextcloud_network:
    driver: bridge
